easy_admin:
    site_name: Books management

    design:
        menu:
            # - { route: 'homepage', label: 'Back to the website', icon: 'home' }
            - { entity: 'Books', label: 'Books', icon: 'map-marker' }

    entities:
        Books:
            class: App\Entity\Books
            # list:
            #     fields:
            #         - author
            #         - { property: 'email', type: 'email' }
            #         - { property: 'createdAt', type: 'datetime' }
            #     sort: ['createdAt', 'ASC']
            #     filters: ['conference']
            # edit:
            #     fields:
            #         - { property: 'conference' }
            #         - { property: 'createdAt', type: datetime, type_options: { disabled: true } }
            #         - 'author'
            #         - { property: 'email', type: 'email' }
            #         - text